name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build for office
      env:
        ORG_GRADLE_PROJECT_MAESTRO_TOKEN: ${{ format('"{0}"', secrets.AL_MAESTRO_TOKEN) }}
        ORG_GRADLE_PROJECT_MAESTRO_DEVICE_NAME: '"office-fire-tv"'
        ORG_GRADLE_PROJECT_MAESTRO_APP_NAME: 'Maestro Media Center'
        ORG_GRADLE_PROJECT_MAESTRO_APP_ID: 'ca.omny.videos.maestro'
        ORG_GRADLE_PROJECT_MAESTRO_PROFILE: '"Al"'
      run: 
        ./gradlew build && mv ./app/build/outputs/apk/debug/app-debug.apk ./office-maestro.apk
    - name: Build for bedroom
      env:
        ORG_GRADLE_PROJECT_MAESTRO_TOKEN: ${{ format('"{0}"', secrets.AL_MAESTRO_TOKEN) }}
        ORG_GRADLE_PROJECT_MAESTRO_DEVICE_NAME: '"fire-tv-auto"'
        ORG_GRADLE_PROJECT_MAESTRO_APP_NAME: 'Maestro Media Center'
        ORG_GRADLE_PROJECT_MAESTRO_APP_ID: 'ca.omny.videos.maestro'
        ORG_GRADLE_PROJECT_MAESTRO_PROFILE: '"Al"'
      run:
        ./gradlew build && mv ./app/build/outputs/apk/debug/app-debug.apk ./fire-tv-auto-maestro.apk
    - name: Build for basement
      env:
        ORG_GRADLE_PROJECT_MAESTRO_TOKEN: ${{ format('"{0}"', secrets.AL_MAESTRO_TOKEN) }}
        ORG_GRADLE_PROJECT_MAESTRO_DEVICE_NAME: '"ye-olde-fire-tv"'
        ORG_GRADLE_PROJECT_MAESTRO_APP_NAME: 'Maestro Media Center'
        ORG_GRADLE_PROJECT_MAESTRO_APP_ID: 'ca.omny.videos.maestro'
        ORG_GRADLE_PROJECT_MAESTRO_PROFILE: '"Al"'
      run:
        ./gradlew build && mv ./app/build/outputs/apk/debug/app-debug.apk ./ye-olde-fire-tv-maestro.apk
    - name: Build for parents
      env:
         ORG_GRADLE_PROJECT_MAESTRO_TOKEN: ${{ format('"{0}"', secrets.PARENTS_MAESTRO_TOKEN) }}
         ORG_GRADLE_PROJECT_MAESTRO_DEVICE_NAME: '"mom-fire-tv"'
         ORG_GRADLE_PROJECT_MAESTRO_APP_NAME: 'Maestro Media Center'
         ORG_GRADLE_PROJECT_MAESTRO_APP_ID: 'ca.omny.videos.maestro'
         ORG_GRADLE_PROJECT_MAESTRO_PROFILE: '"Deb"'
       run:
         ./gradlew build && mv ./app/build/outputs/apk/debug/app-debug.apk ./mom-fire-tv-maestro.apk
      
      
    - name: Upload for office
      uses: tpaschalis/s3-sync-action@master
      with: 
       args: --acl public-read
      env:
        FILE: ./office-maestro.apk
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: Upload for bedroom
      uses: tpaschalis/s3-sync-action@master
      with: 
       args: --acl public-read
      env:
        FILE: ./fire-tv-auto-maestro.apk
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload for basement
      uses: tpaschalis/s3-sync-action@master
      with: 
       args: --acl public-read
      env:
        FILE: ./ye-olde-fire-tv.apk
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Upload for parents
      uses: tpaschalis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        FILE: ./mom-fire-tv.apk
        AWS_REGION: 'us-east-1'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
