name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      env:
        MAESTRO_TOKEN: ${{ secrets.AL_MAESTRO_TOKEN }}
        MAESTRO_DEVICE_NAME: office-fire-tv
        MAESTRO_APP_NAME=Maestro Media Center
        MAESTRO_APP_ID=ca.omny.videos.maestro
      run: ./gradlew build
