name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: download secret key
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-1" # optional: defaults to us-east-1
        run: aws s3 cp s3://${AWS_S3_BUCKET}/maestrokeys/maestrokeystore /home/runner/work/maestro-android/maestro-android/app/maestrokeystore --region ${AWS_REGION} $*
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build for fire tv
        env:
          ORG_GRADLE_PROJECT_MAESTRO_TOKEN: ${{ format('"{0}"', secrets.AL_MAESTRO_TOKEN) }}
          ORG_GRADLE_PROJECT_MAESTRO_DEVICE_NAME: '"office-fire-tv"'
          ORG_GRADLE_PROJECT_MAESTRO_APP_NAME: "Maestro Media Center"
          ORG_GRADLE_PROJECT_MAESTRO_APP_ID: "ca.omny.videos.maestro"
          ORG_GRADLE_PROJECT_MAESTRO_PROFILE: '"Al"'
          ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS: "maestrokey"
          ORG_GRADLE_PROJECT_RELEASE_STORE_FILE: "maestrokeystore"
          ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD }}
          ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD }}
        run: ./gradlew assembleRelease && mv ./app/build/outputs/apk/release/app-release.apk ./fire-tv-maestro.apk

      - name: Upload for fire tv
        run: aws s3 cp ${FILE} s3://${AWS_S3_BUCKET}/${FILE} --acl public-read --metadata maestro-version=1.4
        env:
          FILE: fire-tv-maestro.apk
          AWS_REGION: "us-east-1"
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
